#!/usr/bin/env bash

IMAGE_NAME=ros-melodic
CONTAINER_NAME=`docker ps --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`

if [[ -z $CONTAINER_NAME ]]; then
    echo "Container not running, starting it"
    DIR=`dirname $0`
    bash -c "$DIR/start"
fi

CONTAINER_NAME=`docker ps --filter status=running --filter ancestor=$IMAGE_NAME --format "{{.Names}}"`
docker exec -it $CONTAINER_NAME $SHELL
