#!/usr/bin/env bash

IMAGE_NAME=ros-melodic
VIDEO_DEVICE=/dev/video0
# Get the group number of the video group, docker groups may differ
VIDEO_GROUP=`stat -c "%g" $VIDEO_DEVICE`

# Run the container with shared X11
docker run\
  --net=host\
  -e SHELL\
  -e DISPLAY\
  -e DOCKER=1\
  -v "$HOME:$HOME:rw"\
  -v "/tmp/.X11-unix:/tmp/.X11-unix:rw"\
  --device=$VIDEO_DEVICE:/dev/video0 \
  --group-add=$VIDEO_GROUP \
  --rm \
  -it $IMAGE_NAME $SHELL
